# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Tell Read the Docs to use Sphinx to build HTML docs
sphinx:
  configuration: docs/conf.py   # relative to repository root
  fail_on_warning: false        # optional, but avoids build stops on warnings

# Optional: build additional formats (PDF, ePub)
formats:
  - htmlzip
  - pdf
  - epub

# Install Python dependencies required to build docs
python:
  install:
    - requirements: docs/requirements.txt
